services:
  antaris-sql-test:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: antaris-sql-test
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD_TEST}
    volumes:
      - antaris_sql_test_data:/var/opt/mssql
    networks:
      - antaris-net
    healthcheck:
      test: [
          "CMD-SHELL",
          'echo "Using DB password: $MSSQL_SA_PASSWORD" ', #&& /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 30

  antaris-api:
    depends_on:
      antaris-sql-test:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      ConnectionStrings__DefaultConnection: >
        Server=antaris-sql-test;
        Database=AntarisBlogTest;
        User Id=sa;
        Password=${DB_PASSWORD_TEST};
        TrustServerCertificate=True;
        MultipleActiveResultSets=True;

volumes:
  antaris_sql_test_data:
